services:
  pontus:
    build: .
    container_name: pontus
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
  postgres:
    image: postgres:17
    container_name: pontus-postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pontus
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=pontus